baseURL = 'https://yuvannithit.github.io/'
languageCode = 'en-us'
title = 'Yuvannithi Thirumaran'
timeout = 600000

[params]
  # Add this line:
  description = "Explore the Aerospace Dynamics and Control Engineering portfolio of Yuvannithi Thirumaran. Discover projects, experience, and insights into flight systems."